### ISSUE TITLE
Can you offer the model and code of mcnet without residual？

### ISSUE THREAD

**Issue by xukai8** [rubenvillegas/iclr2017mcnet#8]
Thank you very much.

**Comment by rubenvillegas** [comment]
Sorry for the very late response. For mcnet without residual, all you need to do is remove the tf.add operations in the decoder and just replace them with depool3, depool2 and depool1 for each of the decoder layers. I will try to find the pretrained models and add the links to download them. I have to look for them though. Otherwise, you can just modify the decoder as mentioned before and train.
